services:
  db:
    image: thomasidgeo/idgeo-postgis:16.3.3
    container_name: postgis_idgeo # peut-être modifié
    restart: always
    environment:
      POSTGRES_USER: pguser # Personnalisable
      POSTGRES_PASSWORD: achanger # Personnalisable
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432" # Personnalisable
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata: