services:
  db:
    image: thomasidgeo/idgeo-postgis:17.3.6
    # Construction du container avec paramètres personnalisés
    build:
        context: .
        dockerfile: Dockerfile
    container_name: postgis # peut-être modifié
    restart: always
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
      - ./init-scripts:/docker-entrypoint-initdb.d
    user : "999:999" #user postgres machine
    ports:
      - "${POSTGRES_PORT}:5432" # Personnalisable depuis init-scripts/init-env.sh
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata: